### ISSUE TITLE
Error at rails s

### ISSUE THREAD

**Issue by benbonnet** [andie-chernysh/omniauth-tictail#1]
With a regular omniauth config through devise, I get the following error (conf'ed in devise.rb) :

`.../devise/omniauth/config.rb:40:in`autoload_strategy': Could not find a strategy with name `Tictail'. Please ensure it is required or explicitly set it using the :strategy_class option. (Devise::OmniAuth::StrategyNotFound)```

When trying a regular omniauth use (set via config/initializers/omniauth.rb), I get the following :

`/lib/omniauth/builder.rb:50:in`rescue in provider': Could not find matching strategy for :tictail. You may need to install an additional gem (such as omniauth-tictail). (LoadError)`

I'm not experienced enough to understand the problem, but it feels like this is just a naming problem/variable definitions

Hope to try it out sometimes;
Best

**Comment by Spone** [comment]
Same problem here:

```
/var/lib/gems/2.1.0/gems/omniauth-1.2.2/lib/omniauth/builder.rb:50:in `rescue in provider': Could not find matching strategy for :tictail. You may need to install an additional gem (such as omniauth-tictail). (LoadError)
        from /var/lib/gems/2.1.0/gems/omniauth-1.2.2/lib/omniauth/builder.rb:47:in `provider'
        from /vagrant/config/initializers/omniauth.rb:2:in `block in <top (required)>'
        from /var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
        from /var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
        from /var/lib/gems/2.1.0/gems/omniauth-1.2.2/lib/omniauth/builder.rb:6:in `initialize'
        from /var/lib/gems/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/stack.rb:43:in `new'
        from /var/lib/gems/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/stack.rb:43:in `build'
        from /var/lib/gems/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/stack.rb:118:in `block in build'
        from /var/lib/gems/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/stack.rb:118:in `each'
        from /var/lib/gems/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/stack.rb:118:in `inject'
        from /var/lib/gems/2.1.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/stack.rb:118:in `build'
        from /var/lib/gems/2.1.0/gems/railties-4.2.4/lib/rails/engine.rb:502:in `app'
        from /var/lib/gems/2.1.0/gems/railties-4.2.4/lib/rails/application/finisher.rb:34:in `block in <module:Finisher>'
        from /var/lib/gems/2.1.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
        from /var/lib/gems/2.1.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
        from /var/lib/gems/2.1.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
        from /usr/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /usr/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /usr/lib/ruby/2.1.0/tsort.rb:345:in `each'
        from /usr/lib/ruby/2.1.0/tsort.rb:345:in `call'
        from /usr/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
        from /usr/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
        from /usr/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
        from /var/lib/gems/2.1.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
        from /var/lib/gems/2.1.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
        from /vagrant/config/environment.rb:5:in `<top (required)>'
        from /vagrant/config.ru:3:in `require'
        from /vagrant/config.ru:3:in `block in <main>'
        from /var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
        from /var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
        from /vagrant/config.ru:in `new'
        from /vagrant/config.ru:in `<main>'
        from /var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
        from /var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
        from /var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
        from /var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
        from /var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
        from /var/lib/gems/2.1.0/gems/railties-4.2.4/lib/rails/commands/server.rb:61:in `app'
        from /var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
        from /var/lib/gems/2.1.0/gems/railties-4.2.4/lib/rails/commands/server.rb:139:in `log_to_stdout'
        from /var/lib/gems/2.1.0/gems/railties-4.2.4/lib/rails/commands/server.rb:78:in `start'
        from /var/lib/gems/2.1.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:80:in `block in server'
        from /var/lib/gems/2.1.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /var/lib/gems/2.1.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /var/lib/gems/2.1.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /var/lib/gems/2.1.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by benbonnet** [comment]
tic tail tells you it has oauth… but.

let's just read this : https://tictail.com/developers/documentation/authentication/
it's like unofficially not available  (:

Not surprised this one is not listed in the omniauth strategies (https://github.com/intridea/omniauth/wiki/List-of-Strategies)

**Comment by chashmeetsingh** [comment]
include gem 'omniauth-tictail' in your gemfile and run bunlde install

**Comment by benbonnet** [comment]
@chashmeetsingh LOL
ok now, define tictail in devise.rb or in your omniauth conf file

waiting to have your feedback on this one
